### ISSUE TITLE
Brew is required

### ISSUE THREAD

**Issue by aalkhodiry** [MohamedAlosaili/gog#1]
I love what you did with this project but I can see that brew is required.

https://github.com/MohamedAlosaili/gog/blob/88629779847b8d150fb7b8479155a74734983597/cmd/new/template/justfile#L17C5-L17C23

**Comment by MohamedAlosaili** [comment]
@aalkhodiry Thanks for your great insight. I removed `brew install goose` and now it's an embedded command [`justfile`](https://github.com/MohamedAlosaili/gog/blob/main/cmd/new/template/justfile)
